version: "3.7"

services:

  webui:
    build:
      context: ./WebUI
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    environment:
      - MESSAGE="Message from docker compose file to WebUI"

  jobypea:
    build:
      context: ./JobTypeA
      dockerfile: Dockerfile
    ports:
      - "4001:80"
    environment:
      - MESSAGE="Message from docker compose file to JobTypeA"